<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="OrchardCore.Application.Cms.Targets" Version="3.0.0" />
    <PackageVersion Include="OrchardCore.Logging.Serilog" Version="3.0.0" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.9" />
    <PackageVersion Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.50.3" />
  </ItemGroup>
</Project>
